export enum ChatWsEvents {
    SEND_MESSAGE = 'SEND_MESSAGE',
    CREATE_SELF_ROOM = 'CREATE_SELF_ROOM',
    RECEIVED_MESSAGE = 'RECEIVED_MESSAGE',
    FETCH_KEY_BUNDLE = 'FETCH_KEY_BUNDLE',
    NEW_ACCESS_TOKEN = 'NEW_ACCESS_TOKEN',
    FETCH_NOT_DELIVERED_MESSAGES = 'FETCH_NOT_DELIVERED_MESSAGES',
    RECEIVED_ALL_NOT_DELIVERED_MESSAGES = 'RECEIVED_ALL_NOT_DELIVERED_MESSAGES',
    FETCH_RECIPIENT_ID = 'FETCH_RECIPIENT_ID'
}
